/*

Copyright (C) 2008-2020 Michele Martone

This file is part of librsb.

librsb is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

librsb is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public
License along with librsb; see the file COPYING.
If not, see <http://www.gnu.org/licenses/>.

*/
/* @cond INNERDOC */
/* This file was generated by the Makefile */
#include "rsb.h"
#include "rsb_common.h"
#include "rsb_do.h"
rsb_err_t rsb__do_get_matrix_info_from_string(const struct rsb_mtx_t *matrix, const rsb_char_t *mis, void* info, size_t buflen)
{ rsb_err_t errval=RSB_ERR_BADARGS; if(!matrix || !mis || !info)goto err;
if(0 == strcmp(mis,"RSB_MIF_INDEX_STORAGE_IN_BYTES__TO__SIZE_T")){ errval = rsb__do_get_matrix_info(matrix,RSB_MIF_INDEX_STORAGE_IN_BYTES__TO__SIZE_T,info,buflen); goto done;}
if(0 == strcmp(mis,"RSB_MIF_INDEX_STORAGE_IN_BYTES_PER_NNZ__TO__RSB_REAL_T")){ errval = rsb__do_get_matrix_info(matrix,RSB_MIF_INDEX_STORAGE_IN_BYTES_PER_NNZ__TO__RSB_REAL_T,info,buflen); goto done;}
if(0 == strcmp(mis,"RSB_MIF_MATRIX_ROWS__TO__RSB_COO_INDEX_T")){ errval = rsb__do_get_matrix_info(matrix,RSB_MIF_MATRIX_ROWS__TO__RSB_COO_INDEX_T,info,buflen); goto done;}
if(0 == strcmp(mis,"RSB_MIF_MATRIX_COLS__TO__RSB_COO_INDEX_T")){ errval = rsb__do_get_matrix_info(matrix,RSB_MIF_MATRIX_COLS__TO__RSB_COO_INDEX_T,info,buflen); goto done;}
if(0 == strcmp(mis,"RSB_MIF_MATRIX_NNZ__TO__RSB_NNZ_INDEX_T")){ errval = rsb__do_get_matrix_info(matrix,RSB_MIF_MATRIX_NNZ__TO__RSB_NNZ_INDEX_T,info,buflen); goto done;}
if(0 == strcmp(mis,"RSB_MIF_TOTAL_SIZE__TO__SIZE_T")){ errval = rsb__do_get_matrix_info(matrix,RSB_MIF_TOTAL_SIZE__TO__SIZE_T,info,buflen); goto done;}
if(0 == strcmp(mis,"RSB_MIF_MATRIX_FLAGS__TO__RSB_FLAGS_T")){ errval = rsb__do_get_matrix_info(matrix,RSB_MIF_MATRIX_FLAGS__TO__RSB_FLAGS_T,info,buflen); goto done;}
if(0 == strcmp(mis,"RSB_MIF_MATRIX_TYPECODE__TO__RSB_TYPE_T")){ errval = rsb__do_get_matrix_info(matrix,RSB_MIF_MATRIX_TYPECODE__TO__RSB_TYPE_T,info,buflen); goto done;}
if(0 == strcmp(mis,"RSB_MIF_MATRIX_INFO__TO__CHAR_P")){ errval = rsb__do_get_matrix_info(matrix,RSB_MIF_MATRIX_INFO__TO__CHAR_P,info,buflen); goto done;}
if(0 == strcmp(mis,"RSB_MIF_LEAVES_COUNT__TO__RSB_BLK_INDEX_T")){ errval = rsb__do_get_matrix_info(matrix,RSB_MIF_LEAVES_COUNT__TO__RSB_BLK_INDEX_T,info,buflen); goto done;}
done:
return errval;
err: return RSB_ERR_GENERIC_ERROR;
}
/* @endcond */
